export const accessToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2V2aW4iLCJlbWFpbCI6ImtldmluQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3MjIyNTg0MjUsImV4cCI6MTcyMjM0NDgyNSwiYXVkIjoidXNlcnMiLCJpc3MiOiJsb2dpbiIsInN1YiI6IjEifQ.0hxJiKjFEaP43R4TEJhOozOlBQCRG7WTLLeEg4k-b3w';
