export const resetToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJrZXZpbkBnbWFpbC5jb20iLCJpYXQiOjE3MjIyNzM1NDcsImV4cCI6MTcyMjM1OTk0NywiYXVkIjoidXNlcnMiLCJpc3MiOiJmb3JnZXQiLCJzdWIiOiIxIn0.VaY4vmGhS-ZDu-RLmrHIRD7NFjgfef1w_dJU8w7g2lk';
